name: rani-ukamble-group/build_suzuki1
on:
  workflow_call:
jobs:
  build_suzuki:
    runs-on: ubuntu-latest
    container:
      image: alpine
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
    - run: echo "building suzuki...."
    - run: echo "done"
