name: rani-ukamble-group/build_car1
on:
  workflow_call:
jobs:
  build_car:
    runs-on: ubuntu-latest
    container:
      image: alpine
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
    - run: echo "building cars....."
    - run: mkdir build
    - run: cd build
    - run: touch car.txt
    - run: echo "car built1" > car.txt
    - run: echo "done"
